version: "2.1"

services:
  nginx:
    build: ./.docker/nginx/
    container_name: drupal.app
    ports:
      - 80:80
      - 90:90
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"
    networks:
      - server
    depends_on:
      - php
      - node

  php:
    build: ./.docker/php/
    expose:
      - 9000
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"
    networks:
      - server
      - database
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    networks:
      - database
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  drush:
    image: drush/drush
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"
    networks:
      - server
      - database
    depends_on:
      - php

  node:
    build: ./.docker/node/
    volumes:
      - "${PROJECT_ROOT}:/var/www/html"

volumes:
  data:

networks:
  database:
  server:
